### PR TITLE
fix typo 😭

### PR DESCRIPTION
**Pull request by VinSpee**

### CODE REVIEW

**Comment by chrisdemars** [comment]
@VinSpee do you know what happened to the jpg of the logo?

**Comment by VinSpee** [comment]
I replaced it with a png because it shouldn't be a jpg - it's line art not a photo. Do we need a jpg for some reason?

**Comment by seafoam6** [comment]
I don't think it really matters (to me at least) if it's a jpg/png. I typically use jpg for web because it tends to be smaller in the bytes.

**Comment by chrisdemars** [comment]
I guess it doesn't matter. I made the jpg cuz I don't have illustrator and
I used the exact logo that was on the logo.js repo, same JS yellow and what
not.

**Pull request merged**
